// testSessionLogging.js
// Test script to verify session logging works correctly
// This simulates a session to check that JSON logging is properly formatted

import { createRequire } from 'module';
const require = createRequire(import.meta.url);
import { fileURLToPath } from 'url';
import path from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Simulate a session log structure (what should be generated by DiagnosticFlowScreen)
function generateMockSession() {
  return {
    startedAt: Date.now(),
    baseline: {
      valence: 4,
      energy: 5,
      tension: 7,
      clarity: 4,
      control: 3,
      social: 2,
    },
    macroBase: 'overloaded',
    macroFinal: 'overloaded',
    steps: [
      {
        stepIndex: 0,
        cardId: 'L1_control',
        response: 'A',
        selectedBecause: 'gate:control',
        gatesState: {
          control: false,
          clarity: false,
          load: false,
          social: false,
        },
        addedTagsCount: 3,
        addedTags: ['sig.agency.high', 'sig.tension.medium', 'sig.context.work.deadline'],
        addedTagsTruncated: false,
        addedTagsSample: ['sig.agency.high', 'sig.tension.medium', 'sig.context.work.deadline'],
      },
      {
        stepIndex: 1,
        cardId: 'L1_clarity',
        response: 'B',
        selectedBecause: 'gate:clarity',
        gatesState: {
          control: true,
          clarity: false,
          load: false,
          social: false,
        },
        addedTagsCount: 2,
        addedTags: ['sig.clarity.low', 'sig.uncertainty.high'],
        addedTagsTruncated: false,
        addedTagsSample: ['sig.clarity.low', 'sig.uncertainty.high'],
      },
      {
        stepIndex: 2,
        cardId: 'L1_pressure',
        response: 'A',
        selectedBecause: 'gate:load',
        gatesState: {
          control: true,
          clarity: true,
          load: false,
          social: false,
        },
        addedTagsCount: 4,
        addedTags: ['sig.context.work.deadline', 'sig.tension.high', 'sig.fatigue.medium', 'sig.agency.low'],
        addedTagsTruncated: false,
        addedTagsSample: ['sig.context.work.deadline', 'sig.tension.high', 'sig.fatigue.medium', 'sig.agency.low'],
      },
    ],
    output: {
      microKey: 'overloaded.rushed',
      microSource: 'selected',
      confidenceBand: 'high',
      clarityFlag: 'medium',
      needsRefine: false,
      finalEvidenceTagsCount: 9,
      finalEvidenceTagsSample: [
        'sig.agency.high',
        'sig.tension.medium',
        'sig.context.work.deadline',
        'sig.clarity.low',
        'sig.uncertainty.high',
        'sig.tension.high',
        'sig.fatigue.medium',
        'sig.agency.low',
        'sig.context.work.deadline',
      ],
      finalEvidenceTagsTruncated: false,
    },
    endedBy: 'early_exit',
  };
}

function main() {
  console.log('='.repeat(80));
  console.log('TEST SESSION LOGGING');
  console.log('='.repeat(80));
  console.log('');
  console.log('This script generates a mock session log to verify the format.');
  console.log('In real usage, this JSON will be output by DiagnosticFlowScreen.js');
  console.log('with prefix [DEEP_SMOKE_SESSION]');
  console.log('');
  console.log('='.repeat(80));
  console.log('[DEEP_SMOKE_SESSION]');
  console.log('='.repeat(80));
  
  const mockSession = generateMockSession();
  console.log(JSON.stringify(mockSession, null, 2));
  
  console.log('');
  console.log('='.repeat(80));
  console.log('VERIFICATION:');
  console.log('='.repeat(80));
  
  // Verify required fields
  const required = ['startedAt', 'baseline', 'macroBase', 'steps', 'output', 'endedBy'];
  const missing = required.filter(field => !(field in mockSession));
  
  if (missing.length === 0) {
    console.log('✅ All required fields present');
  } else {
    console.log('❌ Missing fields:', missing);
  }
  
  // Verify baseline
  const baselineFields = ['valence', 'energy', 'tension', 'clarity', 'control', 'social'];
  const baselineMissing = baselineFields.filter(field => !(field in mockSession.baseline));
  if (baselineMissing.length === 0) {
    console.log('✅ Baseline has all 6 metrics');
  } else {
    console.log('❌ Baseline missing:', baselineMissing);
  }
  
  // Verify steps
  if (Array.isArray(mockSession.steps) && mockSession.steps.length > 0) {
    const stepFields = ['stepIndex', 'cardId', 'response', 'selectedBecause', 'gatesState', 'addedTagsCount', 'addedTags'];
    const firstStepMissing = stepFields.filter(field => !(field in mockSession.steps[0]));
    if (firstStepMissing.length === 0) {
      console.log('✅ Steps have all required fields');
    } else {
      console.log('❌ Steps missing:', firstStepMissing);
    }
  } else {
    console.log('❌ No steps recorded');
  }
  
  // Verify output
  const outputFields = ['microKey', 'microSource', 'confidenceBand', 'clarityFlag', 'needsRefine', 'finalEvidenceTagsCount'];
  const outputMissing = outputFields.filter(field => !(field in mockSession.output));
  if (outputMissing.length === 0) {
    console.log('✅ Output has all required fields');
  } else {
    console.log('❌ Output missing:', outputMissing);
  }
  
  console.log('');
  console.log('='.repeat(80));
  console.log('This mock session can be used to test fillRuntimeSmokeTests.js:');
  console.log('  1. Save this JSON to scripts/out/deep_smoke_sessions.jsonl');
  console.log('  2. Run: node scripts/fillRuntimeSmokeTests.js');
  console.log('='.repeat(80));
}

main();
